#pragma once

enum Rooms {
	CLUB_HOUSE_F1 = 0x00,
	CLUB_HOUSE_F2 = 0x01,

	HAM_STUDIO_AREA_1 = 0x02,
	HAM_STUDIO_AREA_2 = 0x03,
	HAM_STUDIO_MAIN_HALL = 0x04,
	HAM_STUDIO_FORTUNE = 0x05,
	HAM_STUDIO_SHOPPING = 0x06,
	HAM_STUDIO_NEWS = 0x07,

	VILLAGE_SQUARE = 0x08,
	VILLAGE_DJUNGLE = 0x09,
	VILLAGE_RAINBOW = 0x0A,
	VILLAGE_HAMHAM = 0x0B,
	VILLAGE_SEAHAMS = 0x0C,

	STADIUM_AREA_1 = 0x0D,
	STADIUM_AREA_2 = 0x0E,
	STADIUM_MAIN_HALL = 0x0F,
	STADIUM_DRESSING_ROOM = 0x10,

	BEACH_AREA_1 = 0x11,
	BEACH_AREA_2 = 0x12,
	BEACH_MAIN_HALL = 0x13,
	BEACH_DRESSING_ROOM = 0x14,

	TENNIS_COURT_AREA_1 = 0x15,
	TENNIS_COURT_AREA_2 = 0x16,
	TENNIS_COURT_MAIN_HALL = 0x17,
	TENNIS_COURT_DRESSING_ROOM = 0x18,

	LAWN_AREA_1 = 0x19,
	LAWN_AREA_2 = 0x1A,
	LAWN_MAIN_HALL = 0x1B,
	LAWN_DRESSING_ROOM = 0x1C,

	POOL_AREA_1 = 0x1D,
	POOL_AREA_2 = 0x1E,
	POOL_MAIN_HALL = 0x1F,
	POOL_DRESSING_ROOM = 0x20,
};

/* Based on spawn coord
 * TODO: create spawn coord table for each room
*/
enum WarpPoints {
	CLUB_HOUSE_F1_MAIN_ENTRANCE = 0x110,
	CLUB_HOUSE_F1_SLIDE = 0x100,
	CLUB_HOUSE_F1_LADDER = 0x150,
	CLUB_HOUSE_F1_BED = 0x0,
	CLUB_HOUSE_F2_LADDER = 0x150,
	CLUB_HOUSE_F2_MESSAGE_MACHINE = 0x1E0,
	CLUB_HOUSE_F2_BASKETBALL_MINIGAME_GREEN = 0xE0,
	CLUB_HOUSE_F2_BASKETBALL_MINIGAME_RED = 0x60,

	POOL_AREA_1_MAIN_ENTRANCE = 0x2,
	POOL_AREA_1_LADDER = 0x2,
	POOL_AREA_1_DOOR = 0x2,
	POOL_AREA_2_LADDER = 0x3,
	POOL_AREA_2_INNER_CLOUD = 0x3,
	POOL_AREA_2_OUTER_CLOUD = 0x3,
	POOL_MAIN_HALL_MAIN_ENTRANCE = 0x4,
	POOL_MAIN_HALL_DRESSING = 0x4,
	POOL_MAIN_HALL_LOBY = 0x4,
	POOL_DRESSING_ROOM_MAIN_ENTRANCE = 0x5,

	BEACH_AREA_1_MAIN_ENTRANCE = 0x6,
	BEACH_AREA_1_DOOR = 0x6,
	BEACH_AREA_1_UPPER_ROUTE = 0x6,
	BEACH_AREA_1_LOWER_ROUTE = 0x6,
	BEACH_AREA_2_UPPER_ROUTE = 0x7,
	BEACH_AREA_2_LOWER_ROUTE = 0x7,
	BEACH_MAIN_HALL_MAIN_ENTRANCE = 0x8,
	BEACH_MAIN_HALL_DRESSING = 0x8,
	BEACH_MAIN_HALL_LOBY = 0x8,
	BEACH_DRESSING_ROOM_MAIN_ENTRANCE = 0x9,

	TENNIS_COURT_AREA_1_MAIN_ENTRANCE = 0xA,
	TENNIS_COURT_AREA_1_DOOR = 0xA,
	TENNIS_COURT_AREA_1_RIGHT_ROUTE = 0xA,
	TENNIS_COURT_AREA_2_LEFT_ROUTE = 0xB,
	TENNIS_COURT_MAIN_HALL_MAIN_ENTRANCE = 0xC,
	TENNIS_COURT_MAIN_HALL_LOBY = 0xC,
	TENNIS_COURT_MAIN_HALL_DRESSING_ROOM = 0xC,
	TENNIS_COURT_DRESSING_ROOM_MAIN_ENTRANCE = 0xD,

	STADIUM_AREA_1_MAIN_ENTRANCE = 0xE,
	STADIUM_AREA_1_DOOR = 0xE,
	STADIUM_AREA_1_LOWER_LEFT = 0xE,
	STADIUM_AREA_1_UPPER_LEFT = 0xE,
	STADIUM_AREA_2_LOWER_RIGHT = 0xF,
	STADIUM_AREA_2_UPPER_RIGHT = 0xF,
	STADIUM_MAIN_HALL_MAIN_ENTRANCE = 0x10,
	STADIUM_MAIN_HALL_LOBY = 0x10,
	STADIUM_MAIN_HALL_DRESSING_ROOM = 0x10,
	STADIUM_DRESSING_ROOM_MAIN_ENTRANCE = 0x11,

	LAWN_AREA_1_MAIN_ENTRANCE = 0x12,
	LAWN_AREA_1_DOOR = 0x12,
	LAWN_AREA_1_RIGHT_ROUTE = 0x12,
	LAWN_AREA_2_LEFT_ROUTE = 0x13,
	LAWN_MAIN_HALL_MAIN_ENTRANCE = 0x14,
	LAWN_MAIN_HALL_LOBY = 0x14,
	LAWN_MAIN_HALL_DRESSING_ROOM = 0x14,
	LAWN_DRESSING_ROOM_MAIN_ENTRANCE = 0x15,

	VILLAGE_SQUARE_MAIN_ENTRANCE = 0x16,
	VILLAGE_SQUARE_DJUNGLE = 0x16,
	VILLAGE_SQUARE_RAINBOW = 0x16,
	VILLAGE_SQUARE_HAMHAM = 0x16,
	VILLAGE_SQUARE_SEAHAMS = 0x16,
	VILLAGE_DJUNGLE_MAIN_ENTRANCE = 0x17,
	VILLAGE_RAINBOW_MAIN_ENTRANCE = 0x18,
	VILLAGE_HAMHAM_MAIN_ENTRANCE = 0x19,
	VILLAGE_SEAHAMS_MAIN_ENTRANCE = 0x1A,

	HAM_STUDIO_AREA_1_MAIN_ENTRANCE = 0x0,
	HAM_STUDIO_AREA_1_DOOR = 0x1B,
	HAM_STUDIO_AREA_1_RIGHT_ROUTE = 0x1B,
	HAM_STUDIO_AREA_2_LEFT_ROUTE = 0x0,
	HAM_STUDIO_MAIN_HALL_MAIN_ENTRANCE = 0x1D,
	HAM_STUDIO_MAIN_HALL_FORTUNE  = 0x1D,
	HAM_STUDIO_MAIN_HALL_SHOPPING = 0x1D,
	HAM_STUDIO_MAIN_HALL_NEWS = 0x1D,
	HAM_STUDIO_FORTUNE_MAIN_ENTRANCE = 0x1E,
	HAM_STUDIO_SHOPPING_MAIN_ENTRANCE = 0x1F,
	HAM_STUDIO_NEWS_MAIN_ENTRANCE = 0x20,
};


class LocationData
{
public:
	LocationData();
	~LocationData();
};

